/* StackScope llama.cpp worker — public C interface.
 *
 * The worker uses llama.cpp's C API (llama.h) to load a GGUF, run
 * evaluation, and emit per-token / per-layer events. The gRPC layer is
 * implemented in C++ (worker.cc, generated by the CMake protoc step)
 * and calls into these functions.
 */
#ifndef STACKSCOPE_LLAMACPP_WORKER_H
#define STACKSCOPE_LLAMACPP_WORKER_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Event kinds — must match proto/events.proto EventKind ---- */
typedef enum {
    SS_EVT_UNKNOWN          = 0,
    SS_EVT_TOKEN_BEGIN      = 1,
    SS_EVT_TOKEN_END        = 2,
    SS_EVT_LAYER_BEGIN      = 3,
    SS_EVT_LAYER_END        = 4,
    SS_EVT_ATTENTION_QKV    = 5,
    SS_EVT_ATTENTION_OUTPUT = 7,
    SS_EVT_ACTIVATION       = 8,
    SS_EVT_TENSOR_READ      = 9,
    SS_EVT_LOGITS           = 16,
    SS_EVT_SAMPLE           = 17,
    SS_EVT_MARKER           = 18
} ss_event_kind_t;

typedef struct {
    uint64_t event_id;
    int64_t  timestamp_ns;
    int32_t  kind;
    int32_t  token_index;
    int32_t  layer_index;
    int32_t  head_index;
    int32_t  thread_id;
    int32_t  stream_id;
    int32_t  device_id;
    const uint8_t* payload;
    uint32_t payload_len;
    const char* marker_name;
    int64_t  marker_begin_ns;
    int64_t  marker_end_ns;
    uint64_t marker_correlation_id;
} ss_event_t;

typedef void (*ss_event_sink_fn)(const ss_event_t* e, void* user);

typedef struct ss_worker ss_worker_t;

/* Lifecycle -------------------------------------------------------------- */
ss_worker_t* ss_worker_create(const char* gguf_path,
                              int32_t     n_ctx,
                              const char* device_hint);
void         ss_worker_destroy(ss_worker_t* w);

/* Query loaded model shape (populates *arch as an ASCII string like
 * "llama" or "qwen2"). Buffer must be at least 32 bytes. */
void ss_worker_model_info(const ss_worker_t* w,
                          char arch_out[32],
                          int32_t* n_layers,
                          int32_t* n_heads,
                          int32_t* hidden_size,
                          int32_t* vocab_size);

/* Which device did llama.cpp actually land on for this worker?
 * Fills `device_out` with e.g. "cuda:0" / "hip:1" / "vulkan:0" / "cpu".
 * Buffer must be at least 32 bytes. */
void ss_worker_resolved_device(const ss_worker_t* w, char device_out[32]);

/* ---- Device enumeration ------------------------------------------------
 *
 * llama.cpp compiles-in the backends it was configured with (any subset of
 * CUDA / HIP / Vulkan / Metal / OpenCL / CPU). We surface every accelerator
 * llama.cpp itself reports via the ggml backend registry, plus a coarse
 * probe of the driver runtime for name + memory + compute capability.
 * Static — safe to call before any model is loaded. */
typedef struct {
    char     id[32];               /* "cuda:0", "hip:0", "vulkan:0", "cpu" */
    char     kind[16];              /* "cuda", "hip", "vulkan", "metal", "cpu" */
    char     name[128];             /* "NVIDIA GeForce RTX 4090" */
    uint64_t total_memory_bytes;
    uint64_t free_memory_bytes;
    char     compute_capability[16]; /* "8.9" for Ada; "gfx1100" for RDNA3 */
    char     driver_version[32];
    int32_t  multi_processor_count;
    int32_t  is_integrated;         /* 0/1 */
    int32_t  is_default;            /* 0/1 — one entry only */
} ss_device_info_t;

/* Fill `out` with up to `max` devices, return count actually written.
 * On any backend probe failure, the corresponding entry is skipped rather
 * than aborting the whole enumeration. CPU is always emitted last. */
int32_t ss_enumerate_devices(ss_device_info_t* out, int32_t max);

/* Run inference. Blocks until finished; every event goes through `sink`.
 * `sink` may be called from an internal worker thread — it must be
 * thread-safe. Returns 0 on success, negative on failure. */
int  ss_worker_run(ss_worker_t*     w,
                   const char*      transaction_id,
                   const char*      prompt,
                   int32_t          max_new_tokens,
                   float            temperature,
                   float            top_p,
                   int32_t          top_k,
                   uint64_t         seed,
                   int32_t          capture_level,
                   ss_event_sink_fn sink,
                   void*            user);

/* Monotonic host-clock timestamp in ns; same clock domain other events use. */
int64_t ss_now_ns(void);

#ifdef __cplusplus
}
#endif

#endif  /* STACKSCOPE_LLAMACPP_WORKER_H */
